name: docker-build-workflow

on:
  push: 
    branches: safa
  pull_request:
    branches: safa
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag build-my-dockerfile:$(date +%s)
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.7.2
      with:
       minikube version: 'v1.28.0'
       kubernetes version: 'v1.25.4'
       github token: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Interact with the cluster
      run: kubectl get nodes

    - name: Start Minikube
      run: minikube start

    - name: Load Docker image into Minikube
      run: minikube image load build-my-dockerfile:$(date +%s)
      
    - name: Apply deployment and service yml files
      run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
